title: Welcome to Ivy's Portfolio!
author: Ivy Wang
description: I am a student in the Master of Science in Business Analytics program at the University of Iowa. 
I am good at Python and R programming. I like Photography and Calligraphy.
theme: jekyll-theme-cayman
